### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by adeebakausar** [HRNet/HRNet-MaskRCNN-Benchmark#8]
!python tools/train_net.py --config-file "/usr/local/HRNet-MaskRCNN-Benchmark/configs/hrnet/mask_rcnn_hrnet_w18_1x.yaml"

**Error**
/usr/local/HRNet-MaskRCNN-Benchmark
Traceback (most recent call last):
  File "tools/train_net.py", line 22, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/usr/local/HRNet-MaskRCNN-Benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/usr/local/HRNet-MaskRCNN-Benchmark/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'

**Comment by wondervictor** [comment]
Only PyTorch 1.0.1 is supported.
